name: Deploy mdBook
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jontze/action-mdbook@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          mdbook-version: "~0.4.18"
          use-mermaid: true
          mermaid-version: "~0.10.0"
          use-linkcheck: false
          use-toc: false
          use-opengh: false
      - name: Show mdbook version
        run: mdbook --version
      - name: Show mermaid version
        run: mdbook-mermaid --version
      - name: Make CNAME
        run: echo book.marwood.io > CNAME
